hospital/urls.py
from django.conf.urls import url
from . import views
from .views import HospitalDV,ReserveLV



urlpatterns=[
    url(r'^$',views.hospital_list,name='hospital_list'),
    #url(r'^$',views.HospitalLV.as_view(),name='hospital_list'),
    url(r'(?P<hospital_id>\d+)/new/$', views.reserve_new, name='reserve_new'),
    url(r'reserve_list$', ReserveLV.as_view(), name='reserve_list'),
    url(r'(?P<pk>\d+)/$', HospitalDV.as_view(), name='detail'),
    


    ##Ajax
    url(r'^selectdate/$',views.selectDate,name="select_date"),
    url(r'^selectSido/$',views.selectSido,name="select_sido"),
    url(r'^reserve_cancel/$',views.cancelReserve,name="reserve_cancel"),
    #url(r'^reserve/$',views.reserve,name="reserve"),
]

reserve/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import redirect
from django.conf import settings


urlpatterns = [
    url(r'^$', lambda r:redirect('hospital:hospital_list'),name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^hospital/', include('hospital.urls',namespace='hospital')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns+=[
        url(r'^__debug__/',include(debug_toolbar.urls)),
    ]

reserve/templates/layout.html
{% load static %}
{# bootstrap3 라이브러리 로드 #} 
{% load bootstrap3 %}

{#JQuery#}
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>

{# bootstrap3 라이브러리를 통해 css/javascript 태그 출력 #} 
{#<script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>#}


<!-- 부가적인 테마 -->
<!--<link rel="stylesheet" href="{% static "bootstrap-3.3.2/dist/css/bootstrap-theme.css" %}">-->

<!-- 합쳐지고 최소화된 최신 자바스크립트 -->
<!--<script src="{% static "bootstrap-3.3.2/dist/js/bootstrap.min.js" %}"></script>-->
{% bootstrap_css %}
{% bootstrap_javascript %}


<!doctype <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% block extrastyle %}    {% endblock %}
</head>
<body>
        
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url "root" %}">Home</a></li>
                    <li><a href="#">About</a></li>
                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                        <li><a href="{% url "signup" %} " class="glyphicon glyphicon-user">회원가입</a></li>
                        <li><a href="{% url "login" %}?next={{request.path}}" class="glyphicon glyphicon-log-in">로그인</a></li>
                    {% else %}
                        <li><a href="{% url "hospital:reserve_list"%}" class="glyphicon glyphicon-list-alt">예약내역</a></li>   
                        <li><a href="{% url "profile"  %}" class="glyphicon glyphicon-user">프로필</a></li>
                        <li><a href="{% url "logout" %}?next={{request.path}}" class="glyphicon glyphicon-log-out">로그아웃</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% if messages %}
        <div class="container">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    [{{ message.tags }}]   {# 메세지 Level #}
                    {{ message.message }}  {# 실제 메세지 내용 #}
                </div>
            {% endfor %}
        </div>
    {%endif%}

    {%block content%}
    {%endblock%}
</body>
</html>