hospital/urls.py
from django.conf.urls import url
from . import views
from .views import HospitalDV,ReserveLV



urlpatterns=[
    url(r'^$',views.hospital_list,name='hospital_list'),
    #url(r'^$',views.HospitalLV.as_view(),name='hospital_list'),
    url(r'(?P<hospital_id>\d+)/new/$', views.reserve_new, name='reserve_new'),
    url(r'reserve_list$', ReserveLV.as_view(), name='reserve_list'),
    url(r'(?P<pk>\d+)/$', HospitalDV.as_view(), name='detail'),
    


    ##Ajax
    url(r'^selectdate/$',views.selectDate,name="select_date"),
    url(r'^selectSido/$',views.selectSido,name="select_sido"),
    url(r'^reserve_cancel/$',views.cancelReserve,name="reserve_cancel"),
    #url(r'^reserve/$',views.reserve,name="reserve"),
]

reserve/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import redirect
from django.conf import settings


urlpatterns = [
    url(r'^$', lambda r:redirect('hospital:hospital_list'),name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^hospital/', include('hospital.urls',namespace='hospital')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns+=[
        url(r'^__debug__/',include(debug_toolbar.urls)),
    ]

hospital/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Subject(models.Model):
    code = models.CharField(max_length=3)
    subject = models.CharField(max_length=50)
    class Meta:
        #정렬
        ordering=['code',]

    def __str__(self):
        return str(self.subject)

class Sido(models.Model):
    sidoCode = models.CharField(max_length=2)
    sidoName = models.CharField(max_length=20)

    gunguCode = models.CharField(max_length=6)
    gunguName = models.CharField(max_length=20)

    def __str__(self):
        return str(self.sidoName) + " " + str(self.gunguName)

class Hospital(models.Model):
    name=models.CharField(max_length=150)
    dong = models.CharField(max_length=150)
    addr=models.CharField(max_length=150)
    tel=models.CharField(max_length=14)
    sidogungu = models.ForeignKey(Sido)
    subjects = models.ManyToManyField(Subject)
    
    def GetSubjects(self):
        return list(Hospital.objects.first().subjects.all().values_list('subject',flat=True))

    def __str__(self):
        return str(self.name)

class Time(models.Model):
    hospital = models.ForeignKey(Hospital)
    time = models.TimeField()
    class Meta:
        ordering=["time"]

    def __str__(self):
        return str(self.time)

class Doctor(models.Model):
    hospital = models.ForeignKey(Hospital)
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return str(self.name)

class Reserve(models.Model):
    hospital = models.ForeignKey(Hospital)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    date = models.DateField()
    time = models.ForeignKey(Time)
    doctor = models.ForeignKey(Doctor,null=True)

    #item_set = models.ManyToManyField(Time)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        #이 세개의 칼럼은 유니크해야함
        unique_together=('hospital','doctor','date','time',)

        #verbose_name = "예약내역"

        #정렬
        ordering=['-date','-time']



    

hospital/forms.py
from django import forms
from .models import Reserve,Time,Doctor,Hospital
from django.contrib.admin import widgets
#from datetime import date,time
from django.utils import timezone
from datetimewidget.widgets import DateWidget
from django.forms import ModelForm,Select
from django.core.exceptions import NON_FIELD_ERRORS

class ReserveForm(ModelForm):
    def __init__(self, hospital, *args, **kwargs):
        super().__init__(*args,**kwargs)
        
        #처음에는 null로 세팅
        #hospital_id=self.data['hospital_id']
        #reserve_date = self.data['date']

        #doctor_id = self.data['doctor_id']
        
        '''
        if self.data:
            print(self.data)
            hospital_id = hospital.id
            #hospital_id=self.data['hospital_id']
            reserve_date = self.data['date']

            reserved_list = Time.objects.filter(hospital_id=hospital_id,reserve__date=reserve_date,reserve__doctor_id=doctor_id).values('time')
            self.fields['time'].queryset = exclude_list = Time.objects.filter(hospital_id=hospital_id).exclude(time__in=reserved_list).values_list('time')
        '''
        #의사 목록
        self.fields['doctor'].queryset = Doctor.objects.filter(hospital=hospital)
        self.fields['doctor'].empty_label = None
        
        #self.fields['hospital'].queryset = Hospital.objects.filter(id = hospital.id)
        #self.fields['hospital'].empty_label = None

        print(self.fields['hospital'].queryset)
    class Meta:
        model = Reserve
        fields= ['hospital','doctor','date','time']
        
        #NON_FIELD_ERROR 오버라이드
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "얘약 시간이 없습니다.",
            }
        }


        #예약을 언제 까지 받을지 결정해야함(startDate,endDate)
        dateOptions = {
            'format': 'yyyy-mm-dd',
            'autoclose': True,
            'todayHighlight' : True,
            'startDate':'+1d',
            'endDate':'+7d',
            }
        
        #widgets={'date':DateWidget(attrs={'id':"datepicker"}, usel10n = True, bootstrap_version=3,options=dateOptions)}
        widgets= {
                'date':DateWidget(attrs={'id':"datepicker"}, bootstrap_version=3,options=dateOptions),
                'hospital':forms.HiddenInput(),
            }
        
        

hospital/views.py
from django.core import serializers
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import ReserveForm
from django.http import HttpResponse
import json
import datetime
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import DetailView,ListView
from django.core.exceptions import ValidationError

class HospitalDV(DetailView):
    """
	DetailView 디폴트 지정 속성
	1) 컨텍스트 변수 : object (URLConf 에서 pk 파라미터 값을 활용하여 DB 레코드 조회)
	2) 템플릿 파일 : (모델명소문자_detail.html)
	"""
    model = Hospital

class HospitalLV(ListView):
    model = Hospital
    paginate_by = 10

'''
    def get_context_data(self,**kwargs):
        context = super(HospitalLV,self).get_context_data(**kwargs)
        subject = self.request.GET.get('subject')
        search_text = self.request.GET.get('search_text')
        
        qs = Hospital.objects.all()
        lst = []
        for hospital in qs:
            dic = {}
            dic["id"] = hospital.id
            dic["name"] = hospital.name
            dic["tel"] = hospital.tel
            dic["addr"] = hospital.addr
            dic["subjects"] = hospital.GetSubjects()
            lst.append(dic)
        
        context.update(
            {
                'hospital_list':lst,
                'subject_list':Subject.objects.all(),
                'sido_list':Sido.objects.values('sidoCode','sidoName').distinct(),
            }
        )
        
        return context
        '''
'''
    def get_queryset(self):
        print("get_queryset")
        print(self.kwargs)
        qs = self.model.objects.all()

        try:
            subject = self.kwargs['subject']
            search_text = self.kwargs['search_text']
            print(subject)
        except:
            subject=''
            search_text = ''
        if(search_text!=''):
            qs = qs.filter(name__icontains=search_text,subjects=subject)
        
        return qs
'''
class ReserveLV(ListView):
    model = Reserve

    def get_queryset(self):
        queryset = super(ReserveLV, self).get_queryset()
        
        #병원
        if(self.request.user.user_type==2):
            pass

        #환자, Admin 포함
        else:
            pass
        
        #times = Time.objects.filter(hospital_id=1,time__gte=datetime.datetime.now())
        #현재는 당일 예약 불가능
        now = datetime.datetime.now()
        queryset = queryset.filter(user=self.request.user,date__gte=now)
        return queryset


# Create your views here.
def hospital_list(request):
    qs = Hospital.objects.all()
    subject = request.GET.get('subject')
    search_text = request.GET.get('search_text')

    if search_text:
        qs = qs.filter(name__icontains=search_text,subjects=subject)

    lst = []
    for hospital in qs:
        dic = {}
        dic["id"] = hospital.id
        dic["name"] = hospital.name
        dic["tel"] = hospital.tel
        dic["addr"] = hospital.addr
        dic["subjects"] = hospital.GetSubjects()
        lst.append(dic)

    #페이지 처리
    paginator = Paginator(lst,10)#20개 보여주기

    page = request.GET.get('page')

    try:
        hospitals = paginator.page(page)
    except PageNotAnInteger:
        hospitals = paginator.page(1)
    except EmptyPage:
        hospitals = paginator.page(paginator.num_pages)

    return render(request,'hospital/hospital_list.html',{
        'hospital_list':hospitals,
        'subject_list':Subject.objects.all(),
        #나중에는 sido만 나가게 변경할것
        'sido_list':Sido.objects.values('sidoCode','sidoName').distinct(),
        
    })



@login_required
def reserve_new(request,hospital_id):
    hospital = get_object_or_404(Hospital,id = hospital_id)
    if request.method=="POST":
        print(request.POST)
        form = ReserveForm(hospital,request.POST)
        
        if form.is_valid():
            print(form.cleaned_data)

            #form fields 땜에 validation 체크를 여기서
            '''
            if Reserve.objects.filter(hospital=hospital_id, doctor=form.cleaned_data['doctor'],
                time=form.cleaned_data['time'],date=form.cleaned_data['date']).exists():
                raise ValidationError('Solution with this Name already exists for this problem')
            '''
            print("after cleaned_data")            
            #다시
            # 동영상 볼것
            
            reserve = form.save(commit=False)
            reserve.user = request.user
            reserve.hospital = hospital
            reserve.save()
            form.save_m2m()
            
            return redirect('hospital:reserve_list')
        else:
            print("not valid!!!!!!!!!")
    else:
        form = ReserveForm(hospital)
    
    return render(request,'hospital/reserve_form.html',{
            'form':form,
            'hospital_info':hospital,
    })

#시간을 문자열로
def timeConvertor(o):
    if isinstance(o, datetime.time):
        return o.__str__()

#Ajax
@require_POST
def selectDate(request):
    hospital_id=request.POST.get('hospital_id',None)
    reserve_date=request.POST.get('reserve_date',None)
    doctor_id = request.POST.get('doctor_id',None)

    #예약되어있는 리스트
    reserved_list = Time.objects.filter(hospital_id=hospital_id,reserve__date=reserve_date,reserve__doctor_id=doctor_id).values('time')
    exclude_list = Time.objects.filter(hospital_id=hospital_id).exclude(time__in=reserved_list).values_list('id','time')
    qs_json = json.dumps(list(exclude_list),default=timeConvertor)
    context = {
        'data':qs_json,
        }
    
    return HttpResponse(json.dumps(context))

@require_POST
def selectSido(request):
    sidoCode = request.POST.get('sidoCode',None)
    gunguList = list(Sido.objects.filter(sidoCode=sidoCode).values_list('gunguCode','gunguName'))
    gunguJson = json.dumps(gunguList)
    context={
        'data':gunguJson,
    }
    return HttpResponse(json.dumps(context))

def cancelReserve(request):
    print(request.POST)
    reserve_id = request.POST.get('reserve_id',None)
    row = Reserve.objects.get(id=reserve_id)
    row.delete()
    return render(request,'hospital/reserve_list.html')

#예약 내역
def reserve(request):
    hospital_id = request.POST.get('hospital_id',None)
    hospital = get_object_or_404(Hospital,id = hospital_id)
    
    #Ajax 일때만 온다.현재는
    if request.method=="POST":
        form = ReserveForm(hospital,request.POST)
        if form.is_valid():
            print("valid")
            #다시 동영상 볼것 -- cleaned_data 에 대해서 알아볼것0303
            print(form.cleaned_data)
            if Reserve.objects.filter(hospital=form.cleaned_data['hospital_id'], doctor=form.cleaned_data['doctor'],
                time=form.cleaned_data['time'],date=form.cleaned_data['date']).exists():
                raise ValidationError('Solution with this Name already exists for this problem')
            '''
            reserve = form.save(commit=False)
            reserve.user = request.user
            reserve.hospital = hospital
            reserve.save()
            form.save_m2m()
            '''
            context={
                'status':1,
                'message':'OK'
            }
            return HttpResponse(json.dumps(context))
        else:
            context={
                'status':1,
                'message':form.errors
            }
            print("=================================")
            print(form.errors)
            print("=================================")
            return HttpResponse(json.dumps(context))
    else:
        form = ReserveForm(hospital)
    
    return render(request,'hospital/reserve_form.html',{
            'form':form,
            'hospital_info':hospital,
    })
    

hospital/templates/hospital/hospital_detail.html
{%extends "hospital/layout.html"%}



{%block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>{{ hospital.name }}</h3>

                

                <hr/>

                <h2>진료과목</h2>

                <ul>
                {% for subject in hospital.subjects.all %}
                    <li>
                        {{ subject.subject }}
                    </li>
                {% endfor %}
                </ul>

                <hr/>

            </div>
        </div>
    </div>
{%endblock%}

hospital/templates/hospital/hospital_list.html
{%extends "hospital/layout.html"%} {% load hospital_extras %}
<script src="http://code.jquery.com/jquery-3.3.1.min.js"></script> {%block content%}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>예약가능한 병원목록</h3>
            
                
            
            <form name="searchForm" action="" method="get" class="form-inline" >
                <div class="form-group">
                    <select name="sido" class="form-control">
                        {%for sido in sido_list%}
                        <option value="{{sido.sidoCode}}">{{sido.sidoName}}</option>
                        {% endfor %}
                    </select>
                    <select name="gungu" class="form-control" style="width:150px;height:35px;">
                        
                    </select>
                    <select name="subject" class="form-control">
                        {%for subject in subject_list%}
                        <option value="{{subject.id}}">{{subject.subject}}</option>
                        {% endfor %}
                    </select>
                    <input type="text" name="search_text" value="{{ search_text }}" class="form-control" />
                    <input type="submit" value="검색" class="btn btn-primary" />
                </div>
            </form>
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <!--<h1><small class="pull-right">45 comments</small> Comments </h1>-->
                    </div>
                    <div class="comments-list">
                        {% for hospital in hospital_list %}
                        <div class="media">
                            <!--<button type="button" class="btn btn-primary pull-right"> 예약하기 </button>-->
                            <a href="{% url "hospital:reserve_new" hospital.id%}" class="btn btn-primary pull-right">예약하기</a>
                            <a class="media-left" href="#">
                                <img src="http://lorempixel.com/40/40/people/">
                            </a>

                            <div class="media-body">
                                <a href="{% url "hospital:detail" hospital.id %}">
                                    <h4 class="media-heading user_name">{{ hospital.name }}</h4>
                                </a>
                                <!--<h6>Wow! this is really great.</h6>-->
                                <ul>
                                    <li>전화번호 - {{hospital.tel}}</li>
                                    <li>주소 - {{hospital.addr}}</li>
                                    <li>진료과목 - {{hospital.subjects|join:","}}</li>
                                </ul>
                            </div>
                        </div>
                        {% endfor %}

                    </div>





                </div>
                
            </div>
            <div class="pagination pull-right">
                    <span class="step-links">
                        {% if hospital_list.has_previous %}
                            <a href="?page={{ hospital_list.previous_page_number }}">previous</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ hospital_list.number }} of {{ hospital_list.paginator.num_pages }}.
                        </span>
                
                        {% if hospital_list.has_next %}
                            <a href="?page={{ hospital_list.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
        </div>



    </div>
</div>
</div>

</div>
<script>
    $(document).ready(function() {
        $("select[name='sido'] option:eq(0)").prop("selected",true);
        $("select[name='sido']").trigger("change");
    });

    $("select[name='sido']").change(function () {
        var sidoCode = $("select[name='sido'] option:selected").val();
        console.log(sidoCode);
        formName = "searchForm";
        objName = "gungu";


        var selectControl = $("form[name='" + formName + "'] select[name='" + objName + "']");
        selectControl.empty();

        $.ajax({
            type: "POST",
            url: "{% url 'hospital:select_sido' %}",

            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'sidoCode': sidoCode,
            },
            dataTyle: "json",
            success: function (response) {
                selectControl.empty();

                var jsonData = JSON.parse(JSON.parse(response).data);
                for (var i = 0; i < jsonData.length; i++) {
                    selectControl.append("<option value=" + jsonData[i][0] + ">" + jsonData[i][1] + "</option>");
                }
            },
            error: function (response) {
            },
        });
    });
</script> {%endblock%}

hospital/templates/hospital/index.html
{%extends "hospital/layout.html"%}
{% load staticfiles %}
{%block content%}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>예약가능한 병원목록</h3>

                <form action="" method="get" class="form-inline">
                    <div class="form-group">
                        <select name="subject" class="form-control">
                            {%for subject in subject_list%}
                                <option value="{{subject.id}}">{{subject.subject}}</option>
                            {% endfor %}
                        </select> 
                        <input type="text" name="search_text" value="{{ search_text }}" class="form-control"/>
                        <input type="submit" value="검색" class="btn btn-primary" />
                    </div>
                </form>
                <div class="list-group contact-group">
                    <a href="#" class="list-group-item">
                        <div class="media">
                            <div class="pull-left">
                                <div class="media-body">
                                    <h4 class="media-heading">John Doe</h4>
                                    <div class="media-content">
                                        <i class="fa fa-map-marker"/>San Francisco
                                        <ul class="list-unstyled">
                                            <li>
                                                <i class="fa fa-skype"/>jode.doe
                                            </li>
                                            <li>
                                                <i class="fa fa-mobile"/>jode.doe
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                
            </div>
        </div>
    </div>
{%endblock%}

hospital/templates/hospital/layout.html
{%extends "layout.html"%}
{% load staticfiles %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
    <link href="http://fonts.googleapis.com/earlyaccess/jejugothic.css" rel="stylesheet" type="text/css">
{% endblock %}

hospital/templates/hospital/reserve_form.html
{% extends "hospital/layout.html" %}
{% load bootstrap3 %}
<script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block content %}
    <div class="container">
        {# 데이트타임 컨트롤  #}
        {{ form.media }}

        <h3>{{ hospital_info.name }} 예약</h3>

        <form id="reserve_form" name="reserve_form" action="{% url "hospital:reserve_new" hospital_info.id%}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary" value="예약"/>
        </form>
    </div>
    <script>
        $(document).ready(function() { 
            $("#id_hospital").val('{{hospital_info.id}}')
         });
        
        
        
        function getData()
        {
            var date = $("#datepicker").data("datetimepicker").getDate(),
                    formatted = date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate();
                console.log(formatted);
                var doctor_id = $("select[name='doctor'] option:selected").val();

                $.ajax({
                    type:"POST",
                    url:"{% url 'hospital:select_date' %}",
                    
                    data:{
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'hospital_id':'{{hospital_info.id}}',
                        'doctor_id':doctor_id,
                        'reserve_date':formatted,
                    },
                    dataTyle:"json",
                    success:function(response){
                        formId="reserve_form";
                        objId="time";
                        var selectControl = $("form[name='"+formId +  "'] select[name='"+objId+"']");
                        selectControl.empty(); 

                        console.log(response);
                        var jsonData = JSON.parse(JSON.parse(response).data);
                        console.log(jsonData);
                        for(var i=0;i<jsonData.length;i++)
                        {
                            //console.log(jsonData[i][0]);
                            selectControl.append("<option value="+ jsonData[i][0] +">"+jsonData[i][1]+"</option>");
                        }
                    },
                    error:function(response){
                        
                    },
                });
            }

            $("select[name='doctor']").change(function(){
                getData();
            });
            $('#datepicker').datetimepicker({format: 'MM/DD/YYYY',defaultDate: "11/1/2018",})
                .on('changeDate', function(e) {
                    getData();
                    //나중에는 함수로 만들어서 의사, 날짜, 시간중 어떤걸 바꿔도 가능하도록 변경할것
                    //var date = e.date.getFullYear()+"-"+(e.date.getMonth()+1)+"-" + e.date.getDate();
                });
    </script>
{% endblock %}


<!--
var hospital_id=$(this).attr('name')
$.ajax({
    type:"POST",
    url:"{% url 'reserve:select_date' %}",
    data: {'hospital_id':name}
});
-->

hospital/templates/hospital/reserve_list.html
{%extends "hospital/layout.html"%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            

            <h2>{{ user.username}}'s 예약내역</h2>

            <table class="table table-striped table-hover">
                <thead>
                    <th>병원명</th>
                    <th>예약날짜</th>
                    <th>예약시간</th>
                    <th>비고</th>
                </thead>
                <tbody>
                    {%for reserve in reserve_list %}
                        <tr>
                            <td>{{reserve.hospital}}</td>
                            <td>{{reserve.date}}</td>
                            <td>{{reserve.time}}</td>
                            <td><button id="reserve_cancel" name="{{reserve.id}}" type="button"  class="btn btn-danger btn-sm">예약취소</button></td>
                        </tr>
                    {%endfor%}
                </tbody>
                
            </table>

            <hr/>

        </div>
    </div>
</div>
<script>
    $("#reserve_cancel").click(function(){
        var pk = $(this).attr('name');
        if(confirm("정말 취소하시겠습니까?"))
        {
            $.ajax({
                type:"POST",
                url:"{% url 'hospital:reserve_cancel' %}",
                
                data:{
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'reserve_id':pk
                    },
                    dataTyle:"json",
                    success:function(response){
                        //나중에는 새로고침 말고 할것
                        location.reload();
                    },
                    error:function(response){
                    console.log("error");
                    },
                });    
        }
        
    });
    
</script>
{%endblock%}